#!/usr/bin/with-contenv bash

DOWNLOAD_DIR="/downloads"

# copy config
[[ ! -f /config/settings.json ]] && cp \
	/defaults/settings.json /config/settings.json

if [ ! -z "$DOWNLOAD_DIR_OVERRIDE" ]; then
	DOWNLOAD_DIR=$DOWNLOAD_DIR_OVERRIDE
	sed -i "/download-dir/c\    \"download-dir\": \"$DOWNLOAD_DIR/complete\"," /config/settings.json
	sed -i "/\"incomplete-dir\"/c\    \"incomplete-dir\": \"$DOWNLOAD_DIR/incomplete\"," /config/settings.json
fi

# make folders
mkdir -p \
	$DOWNLOAD_DIR/{complete,incomplete} /watch

if [ ! -z "$USER" ] && [ ! -z "$PASS" ]; then
	sed -i '/rpc-authentication-required/c\    "rpc-authentication-required": true,' /config/settings.json
	sed -i "/rpc-username/c\    \"rpc-username\": \"$USER\"," /config/settings.json
	sed -i "/rpc-password/c\    \"rpc-password\": \"$PASS\"," /config/settings.json
else
	sed -i '/rpc-authentication-required/c\    "rpc-authentication-required": false,' /config/settings.json
	sed -i "/rpc-username/c\    \"rpc-username\": \"$USER\"," /config/settings.json
	sed -i "/rpc-password/c\    \"rpc-password\": \"$PASS\"," /config/settings.json
fi

if [ ! -z "$WHITELIST" ]; then
	sed -i '/rpc-whitelist-enabled/c\    "rpc-whitelist-enabled": true,' /config/settings.json
	sed -i "/\"rpc-whitelist\"/c\    \"rpc-whitelist\": \"$WHITELIST\"," /config/settings.json
else
	sed -i '/rpc-whitelist-enabled/c\    "rpc-whitelist-enabled": false,' /config/settings.json
	sed -i "/\"rpc-whitelist\"/c\    \"rpc-whitelist\": \"$WHITELIST\"," /config/settings.json
fi

if [ ! -z "$HOST_WHITELIST" ]; then
	sed -i '/rpc-host-whitelist-enabled/c\    "rpc-host-whitelist-enabled": true,' /config/settings.json
	sed -i "/\"rpc-host-whitelist\"/c\    \"rpc-host-whitelist\": \"$HOST_WHITELIST\"," /config/settings.json
else
	sed -i '/rpc-host-whitelist-enabled/c\    "rpc-host-whitelist-enabled": false,' /config/settings.json
	sed -i "/\"rpc-host-whitelist\"/c\    \"rpc-host-whitelist\": \"$HOST_WHITELIST\"," /config/settings.json
fi

if [ ! -z "${PEERPORT}" ]; then
    sed -i "/\"peer-port\"/c\    \"peer-port\": ${PEERPORT}," /config/settings.json
    sed -i '/peer-port-random-on-start/c\     "peer-port-random-on-start": false,' /config/settings.json
fi


# permissions
chown abc:abc \
	/config/settings.json \
	$DOWNLOAD_DIR \
	$DOWNLOAD_DIR/complete \
	$DOWNLOAD_DIR/incomplete \
	/watch
